### ISSUE TITLE
detect provider from url

### ISSUE THREAD

**Issue by nchudleigh** [jiin/ng-video-preview#1]
I have been working on some regex statements for detecting YouTube URLs.  Your directive could really use this to detect the host before displaying it.

**Comment by jiin** [comment]
Ya, paste me the regex please :+1:

**Comment by nchudleigh** [comment]
Its not perfect it doesnt handle playlists and certain obscure urls but works for a good majority of cases.

Id be happy to work with you on some for the rest of the providers.  Since I would include them in my project anyways. :)

here 'tis brobeans:

/(?:https?:\/\/|www\.|m\.|^)youtu(?:be\.com\/watch\?(?:.*?&(?:amp;)?)?v=|\.be\/)([\w‌​\-]+)(?:&(?:amp;)?[\w\?=]*)?/g

**Comment by jiin** [comment]
Really thanks, if you want do a pull request I'm glad to pull and update the project. Meanwhile I'll implement and refactor for a new version of ng-video-preview :)
